---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    # Non modifying hooks
  - id: check-added-large-files
    exclude: ^docs/
  - id: check-yaml
  - id: check-ast
  - id: check-builtin-literals
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-toml
  - id: check-vcs-permalinks
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: debug-statements
  - id: detect-private-key
    # Modifying hooks
  - id: requirements-txt-fixer
  - id: end-of-file-fixer
    exclude: ^docs/
  - id: trailing-whitespace
    exclude: ^docs/

# Lock syntax to Python 3.9
- repo: https://github.com/asottile/pyupgrade
  rev: v3.20.0
  hooks:
  - id: pyupgrade
    args: [--py39-plus]

# Keep last to ensure formatting happens after all other fixes
- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
  - id: black
    exclude: ^docs/
  - id: black-jupyter

# Remove Python notebook outputs before commit
- repo: https://github.com/kynan/nbstripout
  rev: 0.8.1
  hooks:
  - id: nbstripout
    exclude: ^(.svn|CVS|.bzr|.hg|.git|__pycache__|.tox|.ipynb_checkpoints|assets|tests/assets/|venv/|.venv/)

# Ensure imports are sorted alphabetically
- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
  - id: isort
    args: ["--profile", "black", "--filter-files"]
    exclude: ^docs/

# Generic complexity lint
- repo: https://github.com/pycqa/flake8
  rev: 7.3.0
  hooks:
  - id: flake8
    args: ['--max-line-length=160', '--extend-ignore=E203', '--per-file-ignores=__init__.py:F401']
    exclude: ^docs/

# Check typing
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.17.1
  hooks:
  - id: mypy
    additional_dependencies:
      - types-requests
    args: [--ignore-missing-imports, --disallow-untyped-defs, --disallow-untyped-calls, --strict-equality]
    exclude: ^docs/
